SecurityPolicies/Areas/CSP/Controllers/CSPController.cs
using System.Web.Mvc;

namespace SecurityPolicies.Areas.CSP.Controllers
{
    public class CSPController : Controller
    {
        [ContentSecurityPolicy("", true)]
        public ActionResult ReportOnly()
        {
            return View();
        }

        [ContentSecurityPolicy("style-src 'self' https://maxcdn.bootstrapcdn.com; script-src https://maxcdn.bootstrapcdn.com", false)]
        public ActionResult ScriptSource()
        {
            return View();
        }

        [ContentSecurityPolicy("style-src 'self'", false)]
        public ActionResult StyleSource()
        {
            return View();
        }

        [ContentSecurityPolicy("style-src 'self' https://maxcdn.bootstrapcdn.com; script-src https://maxcdn.bootstrapcdn.com https://code.jquery.com 'self'", false)]
        public ActionResult UnsafeInlineOff()
        {
            return View();
        }

        [ContentSecurityPolicy("style-src 'self' https://maxcdn.bootstrapcdn.com; script-src https://maxcdn.bootstrapcdn.com https://code.jquery.com 'self' 'unsafe-inline';", false)]
        public ActionResult UnsafeInlineOn()
        {
            return View();
        }

        [ContentSecurityPolicy("", false)]
        public ActionResult CSPwithSRI()
        {
            return View();
        }
    }
}

SecurityPolicies/Areas/FP/Controllers/FPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SecurityPolicies.Areas.FP.Controllers
{
    public class FPController : Controller
    {
        // GET: FP/FP
        public ActionResult UseBrowserFeatures()
        {
            return View();
        }

        [FeaturePolicyFilter]
        public ActionResult BlockedBrowserFeatures()
        {
            return View();
        }
    }
}

SecurityPolicies/Areas/SRI/Controllers/SRIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SecurityPolicies.Areas.SRI.Controllers
{
    public class SRIController : Controller
    {
        // GET: SRI/SRI
        public ActionResult WorkingLink()
        {
            return View();
        }

        public ActionResult BrokenLink()
        {
            return View();
        }

        public ActionResult BrokenLinkWithFallback()
        {
            return View();
        }
    }
}

SecurityPolicies/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SecurityPolicies.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SecurityPolicies/Areas/CSP/Views/CSP/CSPwithSRI.cshtml
@{
    ViewBag.Title = "CSPwithSRI";
}

<h2>CSPwithSRI</h2>

SecurityPolicies/Areas/CSP/Views/CSP/ReportOnly.cshtml
@{
    ViewBag.Title = "ReportOnly";
}

<h2>ReportOnly</h2>

SecurityPolicies/Areas/CSP/Views/CSP/ScriptSource.cshtml
@{
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
@Html.Partial("Menu")
<div class="container body-content">
    <h2>Script-Src</h2>
    In this example, the markup tries to load the Bootstrap CSS & JS from https://maxcdn.bootstrapcdn.com and jQuery from https://code.jquery.com. The Bootstrap CDN is an allowed source in the CSP, but the jQuery CDN is not.
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

SecurityPolicies/Areas/CSP/Views/CSP/StyleSource.cshtml
@{
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    @Html.Partial("Menu")
    <div class="container body-content">
        <h2>Style-Src</h2>
        In this example, the markup tries to load the Bootstrap CSS from https://maxcdn.bootstrapcdn.com but that is not marked as an allowable source.
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

SecurityPolicies/Areas/CSP/Views/CSP/UnsafeInlineOff.cshtml
@{
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    @Html.Partial("Menu")
    <div class="container body-content">
        <h2>Unsafe-Inline Off</h2>
        In this example, inline script that writes some text is blocked because 'unsafe-inline' does not appear in the CSP.<br/>
        <p id="DynamicallyWrittenText"></p>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    
<script type="text/javascript">
    $('#DynamicallyWrittenText').text('I have been inserted by script');
</script>
</body>
</html>

SecurityPolicies/Areas/CSP/Views/CSP/UnsafeInlineOn.cshtml
@{
    Layout = "";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
@Html.Partial("Menu")
<div class="container body-content">
    <h2>Unsafe-Inline On</h2>
    In this example, 'unsafe-inline' is present in the CSP and the text below this line appears.
    <p id="DynamicallyWrittenText"></p>
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#DynamicallyWrittenText').text('I have been inserted by script');
    });
</script>
</body>
</html>

SecurityPolicies/Areas/CSP/Views/Shared/Menu.cshtml
    <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Security Policies", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="navbar-text">Content Security Policy</li>

                <li><a href="@Url.Action("ScriptSource","CSP")">Script-Src</a></li>
                <li><a href="@Url.Action("StyleSource", "CSP")">Style-Src</a></li>
                <li><a href="@Url.Action("UnsafeInlineOff", "CSP")">Unsafe-Inline - Off</a></li>
                <li><a href="@Url.Action("UnsafeInlineOn", "CSP")">Unsafe-Inline - On</a></li>
                <li><a href="@Url.Action("CSPwithSRI", "CSP")">CSP with SRI</a></li>
                <li><a href="@Url.Action("ReportOnly", "CSP")">Report-Only</a></li>
            </ul>
            </div>

        </div>
    </div>

SecurityPolicies/Areas/CSP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    
</head>
<body>
    @Html.Partial("Menu")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

SecurityPolicies/Areas/FP/Views/FP/BlockedBrowserFeatures.cshtml
@{
    ViewBag.Title = "BlockedBrowserFeatures";
}

<h2>BlockedBrowserFeatures</h2>

<div class="row">
    This page has the same code as the UseBrowserFeatures page, but also has a Feature-Policy header that denies any element on the page from using the camera; the permission denial is shown in the browser console.
</div>

<video autoplay></video>

@section scripts
{
    <script>
        const constraints = {
            video: true
        };

        const video = document.querySelector('video');

        navigator.mediaDevices.getUserMedia(constraints).
            then((stream) => { video.srcObject = stream });
    </script>
}

SecurityPolicies/Areas/FP/Views/FP/UseBrowserFeatures.cshtml
@{
    ViewBag.Title = "UseBrowserFeatures";
}

<h2>Use Browser Features</h2>

This page automatically activates the user's camera and streams the result to a &lt;video&gt; element on the page.

<video autoplay></video>

@section scripts
{
    <script>
        const constraints = {
            video: true
        };

        const video = document.querySelector('video');

        navigator.mediaDevices.getUserMedia(constraints).
            then((stream) => {video.srcObject = stream});
    </script>
}

SecurityPolicies/Areas/FP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Security Policies", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="navbar-text">Feature Policy</li>

                    <li><a href="@Url.Action("UseBrowserFeatures","FP")">Using Browser Features</a></li>
                    <li><a href="@Url.Action("BlockedBrowserFeatures", "FP")">Blocked Browser Features</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SecurityPolicies/Areas/SRI/Views/SRI/BrokenLink.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Broken Link</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4uBROKEN" crossorigin="anonymous">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Security Policies", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="navbar-text">Subresource Integrity</li>

                    <li><a href="@Url.Action("WorkingLink")">Working Link</a></li>
                    <li><a href="@Url.Action("BrokenLink")">Broken Link</a></li>
                    <li><a href="@Url.Action("BrokenLinkWithFallback")">Broken Link with fallback</a></li>
                </ul>
            </div>
        </div>
    </div>
    <br /><br /><br />
    <div class="container body-content">
        <div class="row">
            <div class="jumbotron">
                This page uses Bootstrap from http://maxcdn.bootstrapcdn.com with broken integrity attributes so Bootstrap isn't working. Error messages from the integrity check are shown in the browser console.
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=BROKEN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7TxaBROKEN" crossorigin="anonymous"></script>
</body>
</html>

SecurityPolicies/Areas/SRI/Views/SRI/BrokenLinkWithFallback.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Broken Link with Fallback</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Security Policies", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="navbar-text">Subresource Integrity</li>

                    <li><a href="@Url.Action("WorkingLink")">Working Link</a></li>
                    <li><a href="@Url.Action("BrokenLink")">Broken Link</a></li>
                    <li><a href="@Url.Action("BrokenLinkWithFallback")">Broken Link with fallback</a></li>
                </ul>
            </div>
        </div>
    </div>
    <br /><br /><br />
    <div class="container body-content">
        <div class="row">
            <div class="jumbotron">
                The jQuery link on this page has a broken integrity attribute, but we load a known good version of jQuery from our own server instead of from the CDN.
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=BROKEN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/scripts/jquery-3.3.1.js"><\/script>')</script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

SecurityPolicies/Areas/SRI/Views/SRI/WorkingLink.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Working Link</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Security Policies", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="navbar-text">Subresource Integrity</li>
                <li><a href="@Url.Action("WorkingLink")">Working Link</a></li>
                <li><a href="@Url.Action("BrokenLink")">Broken Link</a></li>
                <li><a href="@Url.Action("BrokenLinkWithFallback")">Broken Link with fallback</a></li>
            </ul>
        </div>
    </div>
</div>
<br/><br/><br/>
    <div class="container body-content">
        <div class="row">
            <div class="jumbotron">
                This page uses Bootstrap from http://maxcdn.bootstrapcdn.com with integrity attributes set.
            </div>
        </div>
    </div>
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    <script src="https://code.jquery.com/jquery-2.2.4.js"
            integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

SecurityPolicies/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SecurityPolicies/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SecurityPolicies/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SecurityPolicies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Security Policies", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SRI <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("WorkingLink", "SRI", new {area = "SRI"})">Working Links</a></li>
                            <li><a href="@Url.Action("BrokenLink", "SRI", new {area = "SRI"})">Broken Links</a></li>
                            <li><a href="@Url.Action("BrokenLinkWithFallback", "SRI", new {area = "SRI"})">Broken Link with Fallback</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CSP <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("StyleSource", "CSP", new {area = "CSP"})">Style-Src</a></li>
                            <li><a href="@Url.Action("ScriptSource", "CSP", new {area = "CSP"})">Script-Src</a></li>
                            <li><a href="@Url.Action("UnsafeInlineOff", "CSP", new {area = "CSP"})">Unsafe-Inline - Off</a></li>
                            <li><a href="@Url.Action("UnsafeInlineOn", "CSP", new {area = "CSP"})">Unsafe-Inline - On</a></li>
                            <li><a href="@Url.Action("CSPWithSRI", "CSP", new {area = "CSP"})">CSP plus SRI</a></li>
                            <li><a href="@Url.Action("ReportOnly", "CSP", new {area = "CSP"})">CSP (Report Only)</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">FP <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("UseBrowserFeatures", "FP", new {area = "FP"})">Using Browser Features</a></li>
                            <li><a href="@Url.Action("BlockedBrowserFeatures", "FP", new {area = "FP"})">Blocked Browser Features</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>